version: "3.9"

services:
  wordpress:
    image: wordpress:5.7.2
    # image: wordpress:latest
    ports: 
      - "4500:80"
    volumes:
      # - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./themes:/var/www/html/wp-content/themes
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test_db
    depends_on:
      - db
  
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    # ports:
    #   - "3306:3306"
  
  node:
    build: .
  
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on: 
  #     - wordpress

volumes: 
  db_data: